export enum ERROR_TYPES {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_TOKEN = 'INVALID_TOKEN',
  GET_AREA_FAILED = 'GET_AREA_FAILED',
  SEARCH_CAFES_FAILED = 'SEACH_CAFES_FAILED',
}